server:
  port: 8080

spring:
  application:
    name: api-gateway-service

  cloud:
    gateway:
      default-filters:
        - AddRequestHeader=X-Trace-Id, #{T(java.util.UUID).randomUUID().toString()}

      routes:

        # ================= AUTH SERVICE (Public) =================
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/auth/**
          #        # ================= USER SERVICE =================
#        - id: user-service
#          uri: lb://USER-SERVICE
#          predicates:
#            - Path=/api/users/**
#          filters:
#            - AuthenticationFilter
#            - name: CircuitBreaker
#              args:
#                name: userServiceCB
#                fallbackUri: forward:/fallback/user
#            - name: RequestRateLimiter
#              args:
#                redis-rate-limiter.replenishRate: 10
#                redis-rate-limiter.burstCapacity: 20
#
#        # ================= CART SERVICE =================
#        - id: cart-service
#          uri: lb://CART-SERVICE
#          predicates:
#            - Path=/api/cart/**
#          filters:
#            - AuthenticationFilter
#            - name: CircuitBreaker
#              args:
#                name: cartServiceCB
#                fallbackUri: forward:/fallback/cart
#            - name: RequestRateLimiter
#              args:
#                redis-rate-limiter.replenishRate: 10
#                redis-rate-limiter.burstCapacity: 20
#
#        # ================= ORDER SERVICE =================
#        - id: order-service
#          uri: lb://ORDER-SERVICE
#          predicates:
#            - Path=/api/orders/**
#          filters:
#            - AuthenticationFilter
#            - name: CircuitBreaker
#              args:
#                name: orderServiceCB
#                fallbackUri: forward:/fallback/order
#            - name: RequestRateLimiter
#              args:
#                redis-rate-limiter.replenishRate: 10
#                redis-rate-limiter.burstCapacity: 20
#
#        # ================= PAYMENT SERVICE =================
#        - id: payment-service
#          uri: lb://PAYMENT-SERVICE
#          predicates:
#            - Path=/api/payments/**
#          filters:
#            - AuthenticationFilter
#            - name: CircuitBreaker
#              args:
#                name: paymentServiceCB
#                fallbackUri: forward:/fallback/payment
#            - name: RequestRateLimiter
#              args:
#                redis-rate-limiter.replenishRate: 5
#                redis-rate-limiter.burstCapacity: 10
#  data:
#    redis:
#      host: localhost
#      port: 6379
#
## ================= EUREKA =================
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

## ================= LOGGING =================
logging:
  level:
    "[org.springframework.cloud.gateway]": DEBUG
    "[reactor.netty.http.client]": DEBUG

## ================= ACTUATOR =================
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#
## ================= RESILIENCE4J =================
#resilience4j:
#  circuitbreaker:
#    instances:
#      userServiceCB:
#        slidingWindowSize: 10
#        failureRateThreshold: 50
#      cartServiceCB:
#        slidingWindowSize: 10
#        failureRateThreshold: 50
#      orderServiceCB:
#        slidingWindowSize: 10
#        failureRateThreshold: 50
#      paymentServiceCB:
#        slidingWindowSize: 10
#        failureRateThreshold: 50
