spring:
  datasource:
    username: springuser
    password: pass@777
logging:
  level:
    root: INFO
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
