spring:
  application:
    name: cart-service
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/cartdb}
      uuid-representation: standard

  mongodb:
    host: ${MONGODB_HOST:localhost}
    port: ${MONGODB_PORT:27017}
    database: ${MONGODB_DATABASE:cartdb}

  cache:
    type: redis

server:
  port: 9999

resilience4j:
  circuitbreaker:
    instances:
      productService:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s

  retry:
    instances:
      productService:
        maxAttempts: 3
        waitDuration: 2s

  timelimiter:
    instances:
      productService:
        timeoutDuration: 3s

  bulkhead:
    instances:
      productService:
        maxConcurrentCalls: 10
