spring:
  application:
    name: order-service

  datasource:
    url: jdbc:mysql://localhost:3306/order_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: 7777

  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8083

resilience4j:
  circuitbreaker:
    instances:
      productService:
        slidingWindowSize: 10
        failureRateThreshold: 50
      userService:
        slidingWindowSize: 10
        failureRateThreshold: 50