spring:
  application:
    name: shipping-service

  datasource:
    url: jdbc:mysql://localhost:3306/shopsphere?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: 7777

  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8087

resilience4j:
  circuitbreaker:
    instances:
      inventoryService:
        slidingWindowSize: 10
        failureRateThreshold: 50

  retry:
    instances:
      inventoryService:
        maxAttempts: 3
        waitDuration: 500ms
